### ISSUE TITLE
Retire Archimedes?

### ISSUE THREAD

**Issue by mgsisk** [mgsisk/archimedes#7]
I feel like Inkblot 4.1 may work well as both a general-purpose theme and as a starting point for users wanting to develop their own Webcomic-ready themes, but I'm interested in feedback on this. Inkblot is definitely more complicated and not really bare-bones, but I'm not sure that's a real deterrent to using it as a starter theme. Anyone that would take Archimedes and work it into a custom-built Webcomic-ready theme could probably do the same with Inkblot.

**Comment by Mihari** [comment]
I think that Inkblot is plenty on it's own, especially given the fact there is the integration option with ANY theme. I know I've found it easier to take away what I need from Inkblot then to try to add things back to Archimedes. That's just my two cents on the matter.

**Comment by mgsisk** [comment]
Based on our discussion in mgsisk/inkblot#27 I may turn Archimedes into an Inkblot child theme instead of outright retiring it. This would be approximately in line with it's original intent (a barebones starter theme for Webcomic); it'd just be working off of Inkblot instead of being it's own standalone theme. Still interested in from others, though.

**Comment by mgsisk** [comment]
Archimedes has been converted to an Inkblot child theme.
